spring:
  application:
    name: banking
  security:
    oauth2:
      resourceserver:
        jwt:
          jwks-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000
server:
  port: 8081