server:
  port: 8081

spring:
  application:
    name: bankserver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

logging:
  level:
    org.springframework.security: INFO